#include "scriptLevelShared.h"
#include <TFE_Jedi/Level/rwall.h>
#include <TFE_Jedi/Level/rsector.h>


namespace TFE_ForceScript
{
	// Register enums that are shared by the editor and game script APIs
	void ScriptLevelShared::scriptRegister()
	{
		s32 res = 0;
		asIScriptEngine* engine = (asIScriptEngine*)TFE_ForceScript::getEngine();

		ScriptEnumRegister("SectorFlags1");
		ScriptEnum("SECTOR_FLAG1_EXTERIOR", SEC_FLAGS1_EXTERIOR);
		ScriptEnum("SECTOR_FLAG1_DOOR", SEC_FLAGS1_DOOR);
		ScriptEnum("SECTOR_FLAG1_MAG_SEAL", SEC_FLAGS1_MAG_SEAL);
		ScriptEnum("SECTOR_FLAG1_EXTERIOR_ADJOIN", SEC_FLAGS1_EXT_ADJ);
		ScriptEnum("SECTOR_FLAG1_ICE_FLOOR", SEC_FLAGS1_ICE_FLOOR);
		ScriptEnum("SECTOR_FLAG1_SNOW_FLOOR", SEC_FLAGS1_SNOW_FLOOR);
		ScriptEnum("SECTOR_FLAG1_EXPLODING_WALL", SEC_FLAGS1_EXP_WALL);
		ScriptEnum("SECTOR_FLAG1_PIT", SEC_FLAGS1_PIT);
		ScriptEnum("SECTOR_FLAG1_PIT_ADJOIN", SEC_FLAGS1_EXT_FLOOR_ADJ);
		ScriptEnum("SECTOR_FLAG1_CRUSHING", SEC_FLAGS1_CRUSHING);
		ScriptEnum("SECTOR_FLAG1_NOWALL_DRAW", SEC_FLAGS1_NOWALL_DRAW);
		ScriptEnum("SECTOR_FLAG1_LOW_DAMAGE", SEC_FLAGS1_LOW_DAMAGE);
		ScriptEnum("SECTOR_FLAG1_HIGH_DAMAGE", SEC_FLAGS1_HIGH_DAMAGE);
		ScriptEnum("SECTOR_FLAG1_NO_SMART_OBJ", SEC_FLAGS1_NO_SMART_OBJ);
		ScriptEnum("SECTOR_FLAG1_SMART_OBJ", SEC_FLAGS1_SMART_OBJ);
		ScriptEnum("SECTOR_FLAG1_SAFE_SECTOR", SEC_FLAGS1_SAFESECTOR);
		ScriptEnum("SECTOR_FLAG1_PLAYER", SEC_FLAGS1_PLAYER);
		ScriptEnum("SECTOR_FLAG1_SECRET", SEC_FLAGS1_SECRET);
		// Outlaws
		ScriptEnum("SECTOR_FLAG1_SLOPEDFLOOR", SEC_FLAGS1_SLOPEDFLOOR);
		ScriptEnum("SECTOR_FLAG1_SLOPEDCEILING", SEC_FLAGS1_SLOPEDCEILING);

		ScriptEnumRegister("WallFlags1");
		ScriptEnum("WALL_FLAGS1_TRANSPARENT_MIDTEX", WF1_ADJ_MID_TEX);
		ScriptEnum("WALL_FLAGS1_ILLUM_SIGN", WF1_ILLUM_SIGN);
		ScriptEnum("WALL_FLAGS1_TEX_FLIP", WF1_FLIP_HORIZ);
		ScriptEnum("WALL_FLAGS1_CHANGE_WALL_LIGHT", WF1_CHANGE_WALL_LIGHT);
		ScriptEnum("WALL_FLAGS1_TEX_ANCHORED", WF1_TEX_ANCHORED);
		ScriptEnum("WALL_FLAGS1_WALL_MORPHS", WF1_WALL_MORPHS);
		ScriptEnum("WALL_FLAGS1_SCROLL_TOP_TEX", WF1_SCROLL_TOP_TEX);
		ScriptEnum("WALL_FLAGS1_SCROLL_MID_TEX", WF1_SCROLL_MID_TEX);
		ScriptEnum("WALL_FLAGS1_SCROLL_BOT_TEX", WF1_SCROLL_BOT_TEX);
		ScriptEnum("WALL_FLAGS1_SCROLL_SIGN_TEX", WF1_SCROLL_SIGN_TEX);
		ScriptEnum("WALL_FLAGS1_HIDE_ON_MAP", WF1_HIDE_ON_MAP);
		ScriptEnum("WALL_FLAGS1_SHOW_NORMAL_ON_MAP", WF1_SHOW_NORMAL_ON_MAP);
		ScriptEnum("WALL_FLAGS1_SIGN_ANCHORED", WF1_SIGN_ANCHORED);
		ScriptEnum("WALL_FLAGS1_DAMAGE_WALL", WF1_DAMAGE_WALL);
		ScriptEnum("WALL_FLAGS1_SHOW_AS_LEDGE_ON_MAP", WF1_SHOW_AS_LEDGE_ON_MAP);
		ScriptEnum("WALL_FLAGS1_SHOW_AS_DOOR_ON_MAP", WF1_SHOW_AS_DOOR_ON_MAP);

		ScriptEnumRegister("WallFlags3");
		ScriptEnum("WALL_FLAGS3_ALWAYS_WALK", WF3_ALWAYS_WALK);
		ScriptEnum("WALL_FLAGS3_SOLID", WF3_SOLID_WALL);
		ScriptEnum("WALL_FLAGS3_PLAYER_WALK_ONLY", WF3_PLAYER_WALK_ONLY);
		ScriptEnum("WALL_FLAGS3_CANNOT_FIRE_THRU", WF3_CANNOT_FIRE_THROUGH);

		ScriptEnumRegister("SectorProp");
		ScriptEnumStr(SECTORPROP_FLOOR_HEIGHT);
		ScriptEnumStr(SECTORPROP_CEIL_HEIGHT);
		ScriptEnumStr(SECTORPROP_SECOND_HEIGHT);
		ScriptEnumStr(SECTORPROP_FLOOR_TEX);
		ScriptEnumStr(SECTORPROP_CEIL_TEX);
		ScriptEnumStr(SECTORPROP_AMBIENT);

		ScriptEnumRegister("WallPart");
		ScriptEnumStr(WP_MIDDLE);
		ScriptEnumStr(WP_TOP);
		ScriptEnumStr(WP_BOTTOM);
		ScriptEnumStr(WP_SIGN);
		ScriptEnumStr(WP_MID);
		ScriptEnumStr(WP_BOT);
	}
}